import type { Emotion } from './emotions'

export const EMOTIONS: Record<string, Emotion> = {
  'felicidad': { name: 'Felicidad', cat: 'felicidad', desc: 'Estado de bienestar pleno que surge cuando vivimos en armonía con nosotros mismos y el mundo. La más alta expresión del florecimiento humano.', nivel: 1 },
  'equilibrio_felicidad': { name: 'Equilibrio', cat: 'felicidad', desc: 'Estado de balance interior donde las emociones, pensamientos y acciones fluyen en armonía.', nivel: 2 },
  'satisfaccion_felicidad': { name: 'Satisfacción', cat: 'felicidad', desc: 'Sensación de plenitud que surge al ver cumplidas nuestras necesidades y deseos más profundos.', nivel: 2 },
  'gozo_felicidad': { name: 'Gozo', cat: 'felicidad', desc: 'Alegría profunda y tranquila que impregna el ser, más duradera que el placer fugaz.', nivel: 2 },
  'plenitud_felicidad': { name: 'Plenitud', cat: 'felicidad', desc: 'Sensación de estar completo, de que nada falta. El ser en su máxima expresión.', nivel: 2 },
  'armonia_felicidad': { name: 'Armonía', cat: 'felicidad', desc: 'Concordancia perfecta entre el mundo interior y exterior, entre lo que somos y lo que vivimos.', nivel: 2 },
  'paz_interior_felicidad': { name: 'Paz Interior', cat: 'felicidad', desc: 'Quietud profunda del alma que permanece incluso ante las tormentas externas.', nivel: 2 },
  'relajacion_felicidad': { name: 'Relajación', cat: 'felicidad', desc: 'Liberación del estrés y la tensión, retorno al estado natural de calma del cuerpo y la mente.', nivel: 2 },
  'tranquilidad_felicidad': { name: 'Tranquilidad', cat: 'felicidad', desc: 'Estado sereno y apacible que nos permite afrontar la vida sin agitación ni ansiedad.', nivel: 2 },
  'serenidad_felicidad': { name: 'Serenidad', cat: 'felicidad', desc: 'Claridad mental y emocional que surge de la aceptación profunda de lo que es.', nivel: 2 },
  'placidez_felicidad': { name: 'Placidez', cat: 'felicidad', desc: 'Calma suave y agradable, ausencia de perturbaciones. El descanso del alma.', nivel: 2 },
  'bienestar_felicidad': { name: 'Bienestar', cat: 'felicidad', desc: 'Estado global de salud física, mental y emocional que permite una vida satisfactoria.', nivel: 2 },
  'dicha_felicidad': { name: 'Dicha', cat: 'felicidad', desc: 'Felicidad intensa y radiante, un estado de gracia donde todo parece perfecto.', nivel: 3 },
  'seguridad_felicidad': { name: 'Seguridad', cat: 'felicidad', desc: 'Sensación de estar protegido y confiado, libre del miedo a lo desconocido.', nivel: 3 },
  'mindfulness_felicidad': { name: 'Mindfulness', cat: 'felicidad', desc: 'Atención plena al momento presente, sin juicio ni resistencia. El arte de estar aquí y ahora.', nivel: 3 },
  'meditacion_felicidad': { name: 'Meditación', cat: 'felicidad', desc: 'Práctica de observar la mente para trascenderla, accediendo a estados de profunda quietud.', nivel: 3 },
  'elevacion_felicidad': { name: 'Elevación', cat: 'felicidad', desc: 'Sensación de trascendencia que surge al contemplar la bondad humana o la belleza sublime.', nivel: 3 },
  'florecer_felicidad': { name: 'Florecer', cat: 'felicidad', desc: 'Eudaimonía: el desarrollo pleno del potencial humano hacia su mejor versión posible.', nivel: 3 },
  'saborear_felicidad': { name: 'Saborear', cat: 'felicidad', desc: 'Arte de apreciar y prolongar conscientemente los momentos positivos de la vida.', nivel: 3 },
  'fluir_felicidad': { name: 'Fluir', cat: 'felicidad', desc: 'Estado de absorción total en una actividad donde el tiempo desaparece y el esfuerzo se vuelve gracia. Flow state.', nivel: 3 },
  'sumak_kawsay_felicidad': { name: 'Sumak Kawsay', cat: 'felicidad', desc: 'Buen vivir andino: armonía con la comunidad, la naturaleza y el cosmos. Bienestar colectivo.', nivel: 3 },
  'dulzura_felicidad': { name: 'Dulzura', cat: 'felicidad', desc: 'Ternura suave que endulza las interacciones y hace la vida más amable.', nivel: 4 },
  'hygge_felicidad': { name: 'Hygge', cat: 'felicidad', desc: 'Concepto danés: calidez acogedora compartida, el placer de la comodidad y la buena compañía.', nivel: 4 },
  'sosiego_felicidad': { name: 'Sosiego', cat: 'felicidad', desc: 'Quietud reposada del ánimo. La calma que viene de haber encontrado el propio centro.', nivel: 4 },
  'calma_felicidad': { name: 'Calma', cat: 'felicidad', desc: 'Ausencia de agitación. Estado base de equilibrio que permite responder en lugar de reaccionar.', nivel: 4 },
  'compromiso_felicidad': { name: 'Compromiso', cat: 'felicidad', desc: 'Dedicación profunda a aquello que da sentido. Cuando el deber y el deseo coinciden.', nivel: 4 },

  'amor': { name: 'Amor', cat: 'amor', desc: 'La fuerza más poderosa del universo humano. Energía que nos conecta con el otro y con lo sagrado de la vida.', nivel: 1 },
  'aceptacion_amor': { name: 'Aceptación', cat: 'amor', desc: 'Recibir al otro — y a uno mismo — tal como es, sin condiciones ni expectativas de cambio.', nivel: 2 },
  'compasion_amor': { name: 'Compasión', cat: 'amor', desc: 'Capacidad de sentir el sufrimiento ajeno y querer aliviarlo. Amor en acción ante el dolor.', nivel: 2 },
  'interes_amor': { name: 'Interés', cat: 'amor', desc: 'Atracción genuina hacia el otro. El primer movimiento del alma hacia la conexión.', nivel: 2 },
  'gratitud_amor': { name: 'Gratitud', cat: 'amor', desc: 'Reconocimiento y apreciación de lo recibido. Abre el corazón y multiplica la alegría.', nivel: 2 },
  'solidaridad_amor': { name: 'Solidaridad', cat: 'amor', desc: 'Amor que se expande hacia la comunidad. Unión en el apoyo mutuo ante la adversidad.', nivel: 2 },
  'cordialidad_amor': { name: 'Cordialidad', cat: 'amor', desc: 'Calidez genuina en el trato. El amor expresado en la cortesía y el afecto cotidiano.', nivel: 2 },
  'simpatia_amor': { name: 'Simpatía', cat: 'amor', desc: 'Atracción natural hacia el otro, disposición positiva que facilita la conexión.', nivel: 2 },
  'empatia_amor': { name: 'Empatía', cat: 'amor', desc: 'Capacidad de sentir desde la perspectiva del otro. El puente entre dos mundos interiores.', nivel: 2 },
  'confianza_amor': { name: 'Confianza', cat: 'amor', desc: 'Fe en el otro y en uno mismo. La base sobre la que se construye todo vínculo verdadero.', nivel: 2 },
  'afecto_amor': { name: 'Afecto', cat: 'amor', desc: 'Cariño suave y constante que nutre las relaciones. El amor en su forma más cotidiana.', nivel: 2 },
  'autoestima_amor': { name: 'Autoestima', cat: 'amor', desc: 'Amor propio saludable. La valoración justa y compasiva de uno mismo.', nivel: 2 },
  'amabilidad_amor': { name: 'Amabilidad', cat: 'amor', desc: 'Gentileza en el trato. El amor expresado en los pequeños gestos que hacen el mundo más humano.', nivel: 2 },
  'carino_amor': { name: 'Cariño', cat: 'amor', desc: 'Afecto tierno y protector. La ternura del amor que cuida y protege.', nivel: 2 },
  'ternura_amor': { name: 'Ternura', cat: 'amor', desc: 'Delicadeza amorosa ante lo vulnerable. La suavidad que protege lo frágil.', nivel: 2 },
  'enamoramiento_amor': { name: 'Enamoramiento', cat: 'amor', desc: 'Estado alterado de consciencia donde el otro ocupa todo el espacio interior. Amor en su máxima intensidad.', nivel: 2 },
  'admiracion_amor': { name: 'Admiración', cat: 'amor', desc: 'Reconocimiento maravillado de la excelencia ajena. Amor que eleva y celebra.', nivel: 2 },
  'respeto_amor': { name: 'Respeto', cat: 'amor', desc: 'Reconocimiento de la dignidad del otro. El amor que preserva la libertad y la integridad.', nivel: 2 },
  'deseo_amor': { name: 'Deseo', cat: 'amor', desc: 'Fuerza de atracción que mueve hacia el otro. Eros: el amor que ansía y busca.', nivel: 2 },
  'afinidad_amor': { name: 'Afinidad', cat: 'amor', desc: 'Sensación de sintonía natural con el otro. Reconocerse en alguien.', nivel: 3 },
  'paciencia_amor': { name: 'Paciencia', cat: 'amor', desc: 'Amor que espera sin desesperarse. La virtud de acompañar los tiempos del otro.', nivel: 3 },
  'perdon_amor': { name: 'Perdón', cat: 'amor', desc: 'Liberación del rencor. El acto de amor más difícil y transformador.', nivel: 3 },
  'curiosidad_amor': { name: 'Curiosidad', cat: 'amor', desc: 'Apertura genuina hacia el otro. El deseo de conocer y comprender.', nivel: 3 },
  'agradecimiento_amor': { name: 'Agradecimiento', cat: 'amor', desc: 'Reconocimiento profundo de lo que el otro nos da. Gratitud en su forma más íntima.', nivel: 3 },
  'compartir_amor': { name: 'Compartir', cat: 'amor', desc: 'Dar de lo propio al otro. El amor que multiplica al dividirse.', nivel: 3 },
  'compenetracion_amor': { name: 'Compenetración', cat: 'amor', desc: 'Entendimiento mutuo tan profundo que parece telepático. La fusión de dos formas de ver.', nivel: 3 },
  'anhelo_amor': { name: 'Anhelo', cat: 'amor', desc: 'Deseo profundo y tierno de lo que se ama y no se tiene cerca. Amor en ausencia.', nivel: 3 },
  'afiliacion_amor': { name: 'Afiliación', cat: 'amor', desc: 'Necesidad y gozo de pertenecer a un grupo. El amor como vínculo comunitario.', nivel: 4 },
  'autoaceptacion_amor': { name: 'Autoaceptación', cat: 'amor', desc: 'Recibirse a uno mismo con amor y sin juicio. La paz con la propia historia.', nivel: 4 },
  'agape_amor': { name: 'Ágape', cat: 'amor', desc: 'Amor incondicional y universal. El amor más alto: dar sin esperar nada a cambio.', nivel: 4 },
  'invulnerabilidad_amor': { name: 'Invulnerabilidad', cat: 'amor', desc: 'Fortaleza interior que surge del amor propio. Resistencia emocional ante el daño.', nivel: 4 },
  'sensibilidad_amor': { name: 'Sensibilidad', cat: 'amor', desc: 'Capacidad de ser tocado por el otro y por el mundo. El don de sentir profundamente.', nivel: 4 },
  'autoconfianza_amor': { name: 'Autoconfianza', cat: 'amor', desc: 'Fe en las propias capacidades. El amor propio expresado en la acción.', nivel: 4 },
  'vinculo_amor': { name: 'Vínculo', cat: 'amor', desc: 'Lazo afectivo que une a las personas. La arquitectura invisible del amor.', nivel: 4 },
  'apego_amor': { name: 'Apego', cat: 'amor', desc: 'Necesidad de proximidad con quien amamos. La base segura desde la que exploramos el mundo.', nivel: 4 },
  'atraccion_amor': { name: 'Atracción', cat: 'amor', desc: 'Fuerza magnética hacia el otro. El primer movimiento del amor.', nivel: 4 },
  'fervor_amor': { name: 'Fervor', cat: 'amor', desc: 'Intensidad ardiente del amor. Pasión que se entrega con todo el ser.', nivel: 4 },
  'veneracion_amor': { name: 'Veneración', cat: 'amor', desc: 'Amor reverente ante lo sagrado o lo admirable. El corazón ante lo que trasciende.', nivel: 4 },
  'fascinacion_amor': { name: 'Fascinación', cat: 'amor', desc: 'Atracción hipnótica que absorbe la atención por completo.', nivel: 4 },
  'adoracion_amor': { name: 'Adoración', cat: 'amor', desc: 'Amor que eleva al otro al máximo nivel. Devoción total y rendida.', nivel: 4 },
  'devocion_amor': { name: 'Devoción', cat: 'amor', desc: 'Entrega constante y fiel. El amor como práctica diaria y sagrada.', nivel: 4 },
  'capricho_amor': { name: 'Capricho', cat: 'amor', desc: 'Deseo súbito y pasajero. Amor ligero que saborea sin comprometerse.', nivel: 4 },
  'afan_amor': { name: 'Afán', cat: 'amor', desc: 'Anhelo intenso y activo. El amor que busca y persigue con energía.', nivel: 4 },
  'antojo_amor': { name: 'Antojo', cat: 'amor', desc: 'Deseo repentino y específico. Amor espontáneo que se satisface en el momento.', nivel: 4 },
  'piedad_amor': { name: 'Piedad', cat: 'amor', desc: 'Compasión profunda ante el sufrimiento ajeno. Amor que no puede quedar indiferente.', nivel: 5 },
  'misericordia_amor': { name: 'Misericordia', cat: 'amor', desc: 'Amor que perdona y acoge incluso lo imperdonable. La compasión en su forma más radical.', nivel: 5 },
  'reconocimiento_amor': { name: 'Reconocimiento', cat: 'amor', desc: 'Ver y nombrar el valor del otro. El amor que hace visible lo invisible.', nivel: 5 },
  'querer_amor': { name: 'Querer', cat: 'amor', desc: 'Amor cotidiano y entrañable. El afecto que se construye en la convivencia diaria.', nivel: 5 },
  'embeleso_amor': { name: 'Embeleso', cat: 'amor', desc: 'Absorción encantada en algo o alguien bello. El alma capturada por la belleza.', nivel: 5 },
  'estima_amor': { name: 'Estima', cat: 'amor', desc: 'Valoración sostenida del otro. El amor que permanece más allá de la pasión inicial.', nivel: 5 },
  'pundonor_amor': { name: 'Pundonor', cat: 'amor', desc: 'Amor propio expresado en la dignidad y el honor. La autoestima en acción.', nivel: 5 },
  'caridad_amor': { name: 'Caridad', cat: 'amor', desc: 'Amor que da sin esperar reciprocidad. La virtud del corazón abierto.', nivel: 5 },
  'altruismo_amor': { name: 'Altruismo', cat: 'amor', desc: 'Amor que antepone el bien del otro al propio. El yo que se trasciende.', nivel: 5 },
  'filantropia_amor': { name: 'Filantropía', cat: 'amor', desc: 'Amor a la humanidad expresado en acciones concretas de bien común.', nivel: 5 },
  'prosocialidad_amor': { name: 'Prosocialidad', cat: 'amor', desc: 'Comportamientos que benefician a otros. El amor convertido en conducta social.', nivel: 5 },
  'aprecio_amor': { name: 'Aprecio', cat: 'amor', desc: 'Valoración consciente de lo que el otro aporta a nuestra vida.', nivel: 5 },
  'arrobo_amor': { name: 'Arrobo', cat: 'amor', desc: 'Éxtasis de admiración y amor. El ser transportado más allá de sí mismo.', nivel: 5 },
  'calidez_amor': { name: 'Calidez', cat: 'amor', desc: 'Calor humano que hace sentir bienvenido. El amor en su forma más acogedora.', nivel: 5 },
  'predileccion_amor': { name: 'Predilección', cat: 'amor', desc: 'Preferencia especial por alguien o algo. El amor que elige.', nivel: 5 },

  'alegria': { name: 'Alegría', cat: 'alegria', desc: 'Emoción luminosa y expansiva. La vida celebrándose a sí misma.', nivel: 1 },
  'ilusion_alegria': { name: 'Ilusión', cat: 'alegria', desc: 'Emoción anticipatoria que colorea el futuro de posibilidades. La alegría del porvenir.', nivel: 2 },
  'placer_alegria': { name: 'Placer', cat: 'alegria', desc: 'Satisfacción sensorial y emocional ante lo agradable. La alegría de los sentidos.', nivel: 2 },
  'humor_alegria': { name: 'Humor', cat: 'alegria', desc: 'Capacidad de encontrar lo cómico en la vida. La alegría que relativiza y libera.', nivel: 2 },
  'diversion_alegria': { name: 'Diversión', cat: 'alegria', desc: 'Alegría activa y lúdica. El juego como forma de estar en el mundo.', nivel: 2 },
  'contento_alegria': { name: 'Contento', cat: 'alegria', desc: 'Satisfacción tranquila con lo que se tiene. La alegría sin excesos.', nivel: 2 },
  'euforia_alegria': { name: 'Euforia', cat: 'alegria', desc: 'Alegría intensa y desbordante. El ser en estado de ebullición positiva.', nivel: 2 },
  'entusiasmo_alegria': { name: 'Entusiasmo', cat: 'alegria', desc: 'Energía apasionada hacia algo. La alegría que impulsa y motiva.', nivel: 2 },
  'optimismo_alegria': { name: 'Optimismo', cat: 'alegria', desc: 'Tendencia a esperar lo mejor. La alegría proyectada hacia el futuro.', nivel: 2 },
  'jubilo_alegria': { name: 'Júbilo', cat: 'alegria', desc: 'Alegría desbordante y expresiva. La celebración del alma.', nivel: 2 },
  'distension_alegria': { name: 'Distensión', cat: 'alegria', desc: 'Relajación placentera tras la tensión. El cuerpo que suelta y respira.', nivel: 4 },
  'desenfocado_alegria': { name: 'Desenfocado', cat: 'alegria', desc: 'Estado lúdico donde la mente vaga libremente. La creatividad sin objetivo.', nivel: 4 },
  'congratulacion_alegria': { name: 'Congratulación', cat: 'alegria', desc: 'Alegría compartida por el logro ajeno. La felicidad que se multiplica.', nivel: 4 },
  'chevere_alegria': { name: 'Chévere', cat: 'alegria', desc: 'Expresión latinoamericana de lo que es bueno, agradable y satisfactorio.', nivel: 4 },
  'moral_alta_alegria': { name: 'Moral Alta', cat: 'alegria', desc: 'Estado de ánimo elevado que surge del sentido de propósito y pertenencia.', nivel: 4 },
  'schadenfreude_alegria': { name: 'Schadenfreude', cat: 'alegria', desc: 'Placer ante la desgracia ajena. La sombra de la alegría que nos hace humanos.', nivel: 4 },
  'alborozo_alegria': { name: 'Alborozo', cat: 'alegria', desc: 'Alegría ruidosa y expresiva. La fiesta del alma.', nivel: 4 },
  'algazara_alegria': { name: 'Algazara', cat: 'alegria', desc: 'Bullicio alegre de varias personas. La alegría que se contagia en grupo.', nivel: 4 },
  'expectacion_alegria': { name: 'Expectación', cat: 'alegria', desc: 'Anticipación tensa y emocionada. La alegría en el umbral de lo que viene.', nivel: 4 },
  'encanto_alegria': { name: 'Encanto', cat: 'alegria', desc: 'Deleite ante algo que parece mágico. La alegría hechizada.', nivel: 5 },
  'complacencia_alegria': { name: 'Complacencia', cat: 'alegria', desc: 'Satisfacción por haber complacido o sido complacido. La alegría del acuerdo.', nivel: 5 },
  'frenesi_alegria': { name: 'Frenesí', cat: 'alegria', desc: 'Alegría descontrolada e intensa. La emoción al límite.', nivel: 5 },
  'exito_alegria': { name: 'Éxito', cat: 'alegria', desc: 'Alegría por el logro alcanzado. La satisfacción de ver los esfuerzos dar fruto.', nivel: 5 },
  'elacion_alegria': { name: 'Elación', cat: 'alegria', desc: 'Alegría exaltada por el éxito. La euforia del triunfo.', nivel: 5 },
  'ganas_alegria': { name: 'Ganas', cat: 'alegria', desc: 'Deseo activo y energético de hacer algo. La alegría en movimiento.', nivel: 5 },
  'animo_alegria': { name: 'Ánimo', cat: 'alegria', desc: 'Disposición positiva y enérgica para afrontar la vida.', nivel: 5 },
  'regodeo_alegria': { name: 'Regodeo', cat: 'alegria', desc: 'Placer intenso y prolongado. Deleitarse con algo una y otra vez.', nivel: 5 },
  'consuelo_alegria': { name: 'Consuelo', cat: 'alegria', desc: 'Alivio ante el dolor. La alegría que surge de sentirse acompañado en la tristeza.', nivel: 5 },

  'sorpresa': { name: 'Sorpresa', cat: 'sorpresa', desc: 'Reacción ante lo inesperado que detiene el flujo ordinario y abre el ser a lo nuevo.', nivel: 1 },
  'estupor_sorpresa': { name: 'Estupor', cat: 'sorpresa', desc: 'Sorpresa tan intensa que paraliza. La mente que no puede procesar lo que ve.', nivel: 3 },
  'estupefaccion_sorpresa': { name: 'Estupefacción', cat: 'sorpresa', desc: 'Asombro profundo que deja sin palabras. El ser desbordado por lo extraordinario.', nivel: 3 },
  'conmocion_sorpresa': { name: 'Conmoción', cat: 'sorpresa', desc: 'Perturbación profunda del ánimo ante algo impactante. La sorpresa que sacude.', nivel: 3 },
  'confusion_sorpresa': { name: 'Confusión', cat: 'sorpresa', desc: 'Estado de desorientación ante lo incomprensible. La mente buscando orden en el caos.', nivel: 3 },
  'pasmo_sorpresa': { name: 'Pasmo', cat: 'sorpresa', desc: 'Asombro que deja inmóvil. La sorpresa convertida en quietud.', nivel: 3 },
  'asombro_sorpresa': { name: 'Asombro', cat: 'sorpresa', desc: 'Maravilla ante lo extraordinario. La mente expandida por lo que no esperaba encontrar.', nivel: 3 },
  'anticipacion_sorpresa': { name: 'Anticipación', cat: 'sorpresa', desc: 'Tensión expectante ante lo que viene. La sorpresa anunciada.', nivel: 3 },
  'perplejidad_sorpresa': { name: 'Perplejidad', cat: 'sorpresa', desc: 'Confusión reflexiva ante lo paradójico. La mente que no puede decidir.', nivel: 3 },
  'desconcierto_sorpresa': { name: 'Desconcierto', cat: 'sorpresa', desc: 'Pérdida del rumbo ante lo inesperado. La brújula interior girando sin norte.', nivel: 3 },
  'extraneza_sorpresa': { name: 'Extrañeza', cat: 'sorpresa', desc: 'Sensación de que algo no encaja en el orden conocido. Lo familiar que se vuelve ajeno.', nivel: 3 },
  'desmoralizacion_sorpresa': { name: 'Desmoralización', cat: 'sorpresa', desc: 'Pérdida del ánimo ante lo inesperadamente adverso. La sorpresa que desinfla.', nivel: 3 },

  'tristeza': { name: 'Tristeza', cat: 'tristeza', desc: 'Emoción que señala la pérdida. Proceso necesario de duelo que permite integrar y seguir.', nivel: 1 },
  'agonia_tristeza': { name: 'Agonía', cat: 'tristeza', desc: 'Sufrimiento extremo en el límite de las fuerzas. La tristeza llevada al máximo.', nivel: 2 },
  'resignacion_tristeza': { name: 'Resignación', cat: 'tristeza', desc: 'Aceptación dolorosa de lo que no puede cambiarse. La tristeza que se rinde.', nivel: 2 },
  'desilusion_tristeza': { name: 'Desilusión', cat: 'tristeza', desc: 'Tristeza por el encuentro con la realidad que no cumplió las esperanzas.', nivel: 2 },
  'decepcion_tristeza': { name: 'Decepción', cat: 'tristeza', desc: 'Dolor por expectativas incumplidas. La tristeza de haber confiado y perder.', nivel: 2 },
  'nostalgia_tristeza': { name: 'Nostalgia', cat: 'tristeza', desc: 'Añoranza agridulce del pasado. La tristeza que también tiene algo de amor.', nivel: 2 },
  'soledad_tristeza': { name: 'Soledad', cat: 'tristeza', desc: 'Dolor de la desconexión. La tristeza de sentirse invisible o no acompañado.', nivel: 2 },
  'melancolia_tristeza': { name: 'Melancolía', cat: 'tristeza', desc: 'Tristeza suave y reflexiva. Pena contemplativa que tiene su propia belleza oscura.', nivel: 2 },
  'infelicidad_tristeza': { name: 'Infelicidad', cat: 'tristeza', desc: 'Ausencia persistente de bienestar. La vida que no logra satisfacer.', nivel: 2 },
  'desaliento_tristeza': { name: 'Desaliento', cat: 'tristeza', desc: 'Pérdida del impulso vital. La tristeza que apaga la energía.', nivel: 2 },
  'pesimismo_tristeza': { name: 'Pesimismo', cat: 'tristeza', desc: 'Tendencia a esperar lo peor. La tristeza proyectada en el futuro.', nivel: 2 },
  'desgana_tristeza': { name: 'Desgana', cat: 'tristeza', desc: 'Falta de motivación para hacer lo que antes gustaba. La tristeza que paraliza.', nivel: 2 },
  'aburrimiento_tristeza': { name: 'Aburrimiento', cat: 'tristeza', desc: 'Vacío existencial ante la falta de sentido o estímulo. La tristeza del sinsentido.', nivel: 2 },
  'sufrimiento_tristeza': { name: 'Sufrimiento', cat: 'tristeza', desc: 'Dolor profundo del alma. La experiencia que forja y transforma si se atraviesa.', nivel: 2 },
  'dolor_tristeza': { name: 'Dolor', cat: 'tristeza', desc: 'Señal de que algo importa profundamente. El precio del amor y el apego.', nivel: 2 },
  'duelo_tristeza': { name: 'Duelo', cat: 'tristeza', desc: 'Proceso de elaborar una pérdida. El camino necesario de la tristeza hacia la aceptación.', nivel: 2 },
  'pena_tristeza': { name: 'Pena', cat: 'tristeza', desc: 'Tristeza que se siente por uno mismo o por otro. El corazón que se apena.', nivel: 2 },
  'pesar_tristeza': { name: 'Pesar', cat: 'tristeza', desc: 'Tristeza reflexiva por algo perdido o lamentado. El peso del alma.', nivel: 2 },
  'afliccion_tristeza': { name: 'Aflicción', cat: 'tristeza', desc: 'Tristeza intensa y angustiante. El alma acongojada.', nivel: 2 },
  'desconsuelo_tristeza': { name: 'Desconsuelo', cat: 'tristeza', desc: 'Tristeza sin alivio posible. La pena que no encuentra consuelo.', nivel: 2 },
  'disgusto_tristeza': { name: 'Disgusto', cat: 'tristeza', desc: 'Malestar ante algo que contradice los propios valores o expectativas.', nivel: 2 },
  'amargura_tristeza': { name: 'Amargura', cat: 'tristeza', desc: 'Tristeza resentida. La pena que se agria con el tiempo y la injusticia.', nivel: 2 },
  'frustracion_tristeza': { name: 'Frustración', cat: 'tristeza', desc: 'Malestar por obstáculos que impiden el logro. La energía bloqueada.', nivel: 3 },
  'morina_tristeza': { name: 'Moriña', cat: 'tristeza', desc: 'Melancolía gallega por la tierra y los seres queridos lejanos. Morriña.', nivel: 3 },
  'congoja_tristeza': { name: 'Congoja', cat: 'tristeza', desc: 'Angustia y pena profunda. Tristeza que oprime el pecho y ahoga.', nivel: 3 },
  'abatimiento_tristeza': { name: 'Abatimiento', cat: 'tristeza', desc: 'Postración del ánimo. La tristeza que tumba y quita las fuerzas.', nivel: 3 },
  'tribulacion_tristeza': { name: 'Tribulación', cat: 'tristeza', desc: 'Angustia y pena causadas por adversidades. El alma en medio de la tormenta.', nivel: 4 },
  'desanimo_tristeza': { name: 'Desánimo', cat: 'tristeza', desc: 'Falta de ilusión y energía. La tristeza que apaga el fuego interior.', nivel: 4 },
  'humillacion_tristeza': { name: 'Humillación', cat: 'tristeza', desc: 'Herida de la dignidad. La tristeza que surge de ser rebajado ante los demás.', nivel: 4 },
  'abandono_tristeza': { name: 'Abandono', cat: 'tristeza', desc: 'Dolor de sentirse dejado atrás. La tristeza de la desconexión no elegida.', nivel: 4 },
  'anoranza_tristeza': { name: 'Añoranza', cat: 'tristeza', desc: 'Tristeza por lo que fue y ya no es. La nostalgia más íntima.', nivel: 4 },
  'sehnsucht_tristeza': { name: 'Sehnsucht', cat: 'tristeza', desc: 'Anhelo profundo alemán por algo indefinible e inalcanzable. El deseo de lo infinito.', nivel: 4 },
  'saudade_tristeza': { name: 'Saudade', cat: 'tristeza', desc: 'Melancolía portuguesa por algo amado y ausente. La tristeza más bella del mundo.', nivel: 4 },
  'hastio_tristeza': { name: 'Hastío', cat: 'tristeza', desc: 'Tedio profundo y disgusto de la existencia. La tristeza de quien lo ha visto todo.', nivel: 4 },
  'pesadumbre_tristeza': { name: 'Pesadumbre', cat: 'tristeza', desc: 'Carga pesada de tristeza. El peso que oprime el corazón.', nivel: 4 },
  'grima_tristeza': { name: 'Grima', cat: 'tristeza', desc: 'Sensación desagradable ante algo repulsivo o que pone los dientes largos.', nivel: 4 },
  'desolacion_tristeza': { name: 'Desolación', cat: 'tristeza', desc: 'Tristeza extrema ante la pérdida total. El alma en el desierto.', nivel: 4 },
  'desdicha_tristeza': { name: 'Desdicha', cat: 'tristeza', desc: 'Infelicidad profunda y persistente. La vida que parece negarse a alegrar.', nivel: 5 },
  'agobio_tristeza': { name: 'Agobio', cat: 'tristeza', desc: 'Sensación de estar aplastado por demasiado. La tristeza del exceso y la presión.', nivel: 5 },
  'suspenso_tristeza': { name: 'Suspenso', cat: 'tristeza', desc: 'Tensión ansiosa ante lo incierto. El alma suspendida entre el miedo y la esperanza.', nivel: 5 },
  'desesperanza_tristeza': { name: 'Desesperanza', cat: 'tristeza', desc: 'Pérdida total de la esperanza. La tristeza que ya no espera nada mejor.', nivel: 5 },
  'languidez_tristeza': { name: 'Languidez', cat: 'tristeza', desc: 'Debilidad melancólica del alma. La tristeza que se derrite lentamente.', nivel: 5 },
  'desencanto_tristeza': { name: 'Desencanto', cat: 'tristeza', desc: 'Pérdida del encanto. La tristeza de haber perdido la capacidad de sorprenderse.', nivel: 5 },
  'desengano_tristeza': { name: 'Desengaño', cat: 'tristeza', desc: 'Tristeza de quien descubre que algo no era lo que creía.', nivel: 5 },
  'lastima_tristeza': { name: 'Lástima', cat: 'tristeza', desc: 'Compasión teñida de superioridad. Pena que puede herir si no se maneja con cuidado.', nivel: 5 },
  'chasco_tristeza': { name: 'Chasco', cat: 'tristeza', desc: 'Decepción súbita. La tristeza del engaño descubierto.', nivel: 5 },
  'fracaso_tristeza': { name: 'Fracaso', cat: 'tristeza', desc: 'Tristeza por no haber logrado lo deseado. También, el maestro más duro y honesto.', nivel: 5 },
  'desamparo_tristeza': { name: 'Desamparo', cat: 'tristeza', desc: 'Tristeza de sentirse sin protección ni apoyo. La vulnerabilidad extrema.', nivel: 5 },
  'decaimiento_tristeza': { name: 'Decaimiento', cat: 'tristeza', desc: 'Bajada del ánimo y la energía. La tristeza que debilita.', nivel: 5 },
  'apatia_tristeza': { name: 'Apatía', cat: 'tristeza', desc: 'Indiferencia ante todo. La tristeza que ha quemado incluso la capacidad de sentir.', nivel: 5 },
  'abulia_tristeza': { name: 'Abulia', cat: 'tristeza', desc: 'Falta de voluntad. La tristeza que paraliza hasta el deseo de desear.', nivel: 5 },
  'acidia_tristeza': { name: 'Acidia', cat: 'tristeza', desc: 'Pereza espiritual medieval. La tristeza del alma que no puede moverse hacia el bien.', nivel: 5 },
  'anorexia_tristeza': { name: 'Anorexia', cat: 'tristeza', desc: 'En su sentido emocional: rechazo y falta de apetito vital.', nivel: 5 },
  'esplin_tristeza': { name: 'Esplín', cat: 'tristeza', desc: 'Tedio existencial romántico. El aburrimiento elevado a categoría filosófica.', nivel: 5 },
  'tedio_tristeza': { name: 'Tedio', cat: 'tristeza', desc: 'Aburrimiento profundo y sin horizonte. La tristeza del tiempo que no pasa.', nivel: 5 },
  'conmiseracion_tristeza': { name: 'Conmiseración', cat: 'tristeza', desc: 'Lástima profunda por el sufrimiento ajeno. Compasión que duele.', nivel: 5 },
  'postracion_tristeza': { name: 'Postración', cat: 'tristeza', desc: 'Abatimiento extremo que deja sin fuerzas. La tristeza que postra.', nivel: 5 },
  'murria_tristeza': { name: 'Murria', cat: 'tristeza', desc: 'Tristeza ligera y vaga. Melancolía sin causa clara. La morriña suave.', nivel: 5 },

  'miedo': { name: 'Miedo', cat: 'miedo', desc: 'Emoción primaria de protección ante la amenaza. Señal de alerta que nos mantiene vivos.', nivel: 1 },
  'horror_miedo': { name: 'Horror', cat: 'miedo', desc: 'Miedo extremo mezclado con repulsión. La amenaza que viola lo sagrado.', nivel: 2 },
  'terror_miedo': { name: 'Terror', cat: 'miedo', desc: 'Miedo paralizante de máxima intensidad. El ser ante lo incontrolable.', nivel: 2 },
  'temor_miedo': { name: 'Temor', cat: 'miedo', desc: 'Miedo anticipatorio ante un peligro conocido. La amenaza que se ve venir.', nivel: 2 },
  'fobia_miedo': { name: 'Fobia', cat: 'miedo', desc: 'Miedo irracional e intenso ante estímulos específicos. El miedo que se desconecta de la razón.', nivel: 2 },
  'alarma_miedo': { name: 'Alarma', cat: 'miedo', desc: 'Activación súbita ante una señal de peligro. El cuerpo en alerta máxima.', nivel: 2 },
  'susto_miedo': { name: 'Susto', cat: 'miedo', desc: 'Miedo súbito ante lo inesperado. El sistema nervioso saltando.', nivel: 2 },
  'canguelo_miedo': { name: 'Canguelo', cat: 'miedo', desc: 'Miedo cobarde. El temor que acobarda y hace huir.', nivel: 3 },
  'xenofobia_miedo': { name: 'Xenofobia', cat: 'miedo', desc: 'Miedo y rechazo al extranjero. El miedo al otro que se convierte en odio.', nivel: 4 },
  'homofobia_miedo': { name: 'Homofobia', cat: 'miedo', desc: 'Miedo y rechazo a la diversidad sexual. El prejuicio disfrazado de miedo.', nivel: 4 },
  'intranquilidad_miedo': { name: 'Intranquilidad', cat: 'miedo', desc: 'Agitación interior por la incertidumbre. El miedo en estado de baja intensidad.', nivel: 4 },
  'vulnerabilidad_miedo': { name: 'Vulnerabilidad', cat: 'miedo', desc: 'Conciencia de la propia fragilidad. El miedo que también puede abrir al amor.', nivel: 4 },
  'sobresalto_miedo': { name: 'Sobresalto', cat: 'miedo', desc: 'Reacción física ante lo inesperado. El cuerpo que salta antes que la mente piense.', nivel: 4 },
  'pavor_miedo': { name: 'Pavor', cat: 'miedo', desc: 'Miedo intenso y profundo. Terror que se instala en el cuerpo.', nivel: 5 },
  'sobrecogimiento_miedo': { name: 'Sobrecogimiento', cat: 'miedo', desc: 'Impresión intensa que paraliza el ánimo. Mezcla de miedo y maravilla.', nivel: 5 },
  'coaccion_miedo': { name: 'Coacción', cat: 'miedo', desc: 'Miedo inducido externamente para controlar. El miedo como herramienta de poder.', nivel: 5 },

  'asco': { name: 'Asco', cat: 'asco', desc: 'Rechazo visceral ante lo que contamina o viola los límites del ser. Protección de la integridad.', nivel: 1 },
  'repugnancia_asco': { name: 'Repugnancia', cat: 'asco', desc: 'Asco intenso y físico. El cuerpo que rechaza con toda su fuerza.', nivel: 2 },
  'aversion_asco': { name: 'Aversión', cat: 'asco', desc: 'Rechazo activo y persistente. El asco convertido en postura.', nivel: 2 },
  'rechazo_asco': { name: 'Rechazo', cat: 'asco', desc: 'Negativa a aceptar o acercarse. El no rotundo del ser.', nivel: 2 },
  'repulsion_asco': { name: 'Repulsión', cat: 'asco', desc: 'Fuerza de alejamiento ante lo repugnante. El asco que empuja.', nivel: 4 },
  'nausea_asco': { name: 'Náusea', cat: 'asco', desc: 'Asco físico que amenaza con expulsar. El cuerpo rechazando lo que no puede tolerar.', nivel: 4 },
  'desagrado_asco': { name: 'Desagrado', cat: 'asco', desc: 'Sensación de que algo no gusta ni conviene. El asco en su forma más suave.', nivel: 5 },
  'aprension_asco': { name: 'Aprensión', cat: 'asco', desc: 'Recelo ante lo que puede contaminar o dañar. El asco anticipatorio.', nivel: 5 },
  'repelus_asco': { name: 'Repelús', cat: 'asco', desc: 'Sensación de asco leve y escalofriante. El cuerpo que se eriza.', nivel: 5 },

  'ira': { name: 'Ira', cat: 'ira', desc: 'Energía poderosa de respuesta ante la injusticia o la amenaza. Puede destruir o transformar.', nivel: 1 },
  'agresividad_ira': { name: 'Agresividad', cat: 'ira', desc: 'Ira expresada en comportamientos ofensivos. La energía de la ira sin canalizar.', nivel: 2 },
  'hostilidad_ira': { name: 'Hostilidad', cat: 'ira', desc: 'Actitud permanente de enfrentamiento. La ira convertida en modo de relacionarse.', nivel: 2 },
  'odio_ira': { name: 'Odio', cat: 'ira', desc: 'Ira profunda y persistente. El amor que se corrompió o el miedo que se endureció.', nivel: 2 },
  'rencor_ira': { name: 'Rencor', cat: 'ira', desc: 'Ira guardada y no expresada. El veneno que se fermenta en el interior.', nivel: 2 },
  'furia_ira': { name: 'Furia', cat: 'ira', desc: 'Ira explosiva e incontrolada. La tormenta del alma.', nivel: 2 },
  'colera_ira': { name: 'Cólera', cat: 'ira', desc: 'Ira vehemente y ardiente. La pasión del enfado en toda su intensidad.', nivel: 2 },
  'enfado_ira': { name: 'Enfado', cat: 'ira', desc: 'Ira moderada ante lo que molesta o contraría. La protesta interior.', nivel: 2 },
  'rabia_ira': { name: 'Rabia', cat: 'ira', desc: 'Ira intensa y urgente. La energía primitiva de la supervivencia.', nivel: 2 },
  'indignacion_ira': { name: 'Indignación', cat: 'ira', desc: 'Ira ante la injusticia. La emoción moral que mueve al cambio.', nivel: 2 },
  'impotencia_ira': { name: 'Impotencia', cat: 'ira', desc: 'Ira sin salida. La frustración de no poder cambiar lo que duele.', nivel: 2 },
  'celos_ira': { name: 'Celos', cat: 'ira', desc: 'Ira por la amenaza a lo que se siente propio. Amor y miedo mezclados.', nivel: 2 },
  'envidia_ira': { name: 'Envidia', cat: 'ira', desc: 'Dolor por el bien ajeno. La ira que quiere lo que el otro tiene.', nivel: 2 },
  'antipatia_ira': { name: 'Antipatía', cat: 'ira', desc: 'Rechazo instintivo hacia alguien. La ira en estado de repulsión pasiva.', nivel: 2 },
  'malhumor_ira': { name: 'Malhumor', cat: 'ira', desc: 'Estado de irritación difusa. La ira de bajo nivel que colorea todo.', nivel: 2 },
  'fastidio_ira': { name: 'Fastidio', cat: 'ira', desc: 'Molestia ante lo que entorpece. La ira ante las pequeñas obstrucciones.', nivel: 2 },
  'resentimiento_ira': { name: 'Resentimiento', cat: 'ira', desc: 'Ira guardada por daños percibidos. El rencor que se alimenta de la memoria.', nivel: 2 },
  'tension_ira': { name: 'Tensión', cat: 'ira', desc: 'Estado de ira contenida. La energía que no puede liberarse.', nivel: 3 },
  'agitacion_ira': { name: 'Agitación', cat: 'ira', desc: 'Inquietud intensa del cuerpo y la mente. La ira que no puede quedarse quieta.', nivel: 3 },
  'actitud_ira': { name: 'Actitud', cat: 'ira', desc: 'Postura de desafío. La ira expresada en el lenguaje corporal.', nivel: 3 },
  'violencia_ira': { name: 'Violencia', cat: 'ira', desc: 'Ira que causa daño. La emoción más oscura cuando pierde el control.', nivel: 3 },
  'exasperacion_ira': { name: 'Exasperación', cat: 'ira', desc: 'Irritación extrema ante la repetición de lo que molesta. La ira al límite.', nivel: 3 },
  'desconfianza_ira': { name: 'Desconfianza', cat: 'ira', desc: 'Ira preventiva ante el otro. El escudo del que ha sido herido.', nivel: 3 },
  'impaciencia_ira': { name: 'Impaciencia', cat: 'ira', desc: 'Ira ante la lentitud o la espera. La urgencia que no tolera el tiempo del otro.', nivel: 3 },
  'desamor_ira': { name: 'Desamor', cat: 'ira', desc: 'Extinción del amor. La tristeza y la ira mezcladas ante el fin de un vínculo.', nivel: 3 },
  'despecho_ira': { name: 'Despecho', cat: 'ira', desc: 'Ira y tristeza por amor rechazado. La herida del orgullo en el corazón.', nivel: 3 },
  'desprecio_ira': { name: 'Desprecio', cat: 'ira', desc: 'Ira que degrada al otro. La emoción más corrosiva para las relaciones.', nivel: 3 },
  'enojo_ira': { name: 'Enojo', cat: 'ira', desc: 'Irritación moderada. La ira cotidiana ante lo que contraría.', nivel: 4 },
  'furor_ira': { name: 'Furor', cat: 'ira', desc: 'Ira ciega y desbordada. La pasión que pierde toda razón.', nivel: 4 },
  'irritacion_ira': { name: 'Irritación', cat: 'ira', desc: 'Molestia persistente. La ira que raspa sin estallar.', nivel: 4 },
  'excitacion_ira': { name: 'Excitación', cat: 'ira', desc: 'Activación intensa del sistema nervioso. Ira y energía mezcladas.', nivel: 4 },
  'recelo_ira': { name: 'Recelo', cat: 'ira', desc: 'Desconfianza cautelosa. La ira defensiva que vigila.', nivel: 4 },
  'enemistad_ira': { name: 'Enemistad', cat: 'ira', desc: 'Relación de oposición activa. La ira convertida en postura duradera.', nivel: 4 },
  'animadversion_ira': { name: 'Animadversión', cat: 'ira', desc: 'Antipatía profunda y sostenida. La ira que no olvida ni perdona.', nivel: 4 },
  'indiferencia_ira': { name: 'Indiferencia', cat: 'ira', desc: 'La ira que se convierte en frialdad. El desprecio disfrazado de neutralidad.', nivel: 4 },
  'frialdad_ira': { name: 'Frialdad', cat: 'ira', desc: 'Distancia emocional como forma de ira pasiva. El hielo como arma.', nivel: 4 },
  'racismo_ira': { name: 'Racismo', cat: 'ira', desc: 'Odio basado en la raza. La ira colectiva más primitiva y destructiva.', nivel: 4 },
  'sexismo_ira': { name: 'Sexismo', cat: 'ira', desc: 'Discriminación basada en el género. La ira sistémica disfrazada de norma.', nivel: 4 },
  'misoginia_ira': { name: 'Misoginia', cat: 'ira', desc: 'Odio o desprecio hacia las mujeres. Una de las formas más antiguas de la ira patriarcal.', nivel: 4 },
  'sadismo_ira': { name: 'Sadismo', cat: 'ira', desc: 'Placer ante el sufrimiento ajeno. La ira más oscura del alma humana.', nivel: 5 },
  'insensibilidad_ira': { name: 'Insensibilidad', cat: 'ira', desc: 'Incapacidad de sentir el dolor ajeno. La ira que ha anestesiado la empatía.', nivel: 5 },
  'crueldad_ira': { name: 'Crueldad', cat: 'ira', desc: 'Acción que causa sufrimiento deliberadamente. La ira sin límites ni compasión.', nivel: 5 },
  'despiedad_ira': { name: 'Despiedad', cat: 'ira', desc: 'Ausencia total de misericordia. La ira que no ve al otro como humano.', nivel: 5 },
  'aborrecimiento_ira': { name: 'Aborrecimiento', cat: 'ira', desc: 'Odio y rechazo intensísimos. La ira en su máxima expresión de repulsa.', nivel: 5 },
  'excecracion_ira': { name: 'Execración', cat: 'ira', desc: 'Maldición y rechazo total. La ira sagrada ante lo que se considera abominable.', nivel: 5 },
  'ojeriza_ira': { name: 'Ojeriza', cat: 'ira', desc: 'Mala voluntad persistente hacia alguien. El rencor con nombre propio.', nivel: 5 },
  'detestacion_ira': { name: 'Detestación', cat: 'ira', desc: 'Odio profundo y activo. La ira que no puede tolerar la existencia del otro.', nivel: 5 },
  'encono_ira': { name: 'Encono', cat: 'ira', desc: 'Rencor enconado que busca dañar. La ira que no descansa.', nivel: 5 },
  'sana_ira': { name: 'Saña', cat: 'ira', desc: 'Crueldad encarnizada. La ira que disfruta causando daño.', nivel: 5 },
  'cabreo_ira': { name: 'Cabreo', cat: 'ira', desc: 'Enfado intenso y expresivo. La ira coloquial al máximo.', nivel: 5 },
  'vesania_ira': { name: 'Vesania', cat: 'ira', desc: 'Furia delirante. La ira que ha cruzado la frontera de la razón.', nivel: 5 },
  'mania_ira': { name: 'Manía', cat: 'ira', desc: 'Fijación intensa y perturbadora. La ira convertida en obsesión.', nivel: 5 },
  'escama_ira': { name: 'Escama', cat: 'ira', desc: 'Recelo y sospecha. La ira preventiva del que ya fue herido.', nivel: 5 },
  'sospecha_ira': { name: 'Sospecha', cat: 'ira', desc: 'Desconfianza basada en indicios. La ira que investiga antes de actuar.', nivel: 5 },
  'pelusa_ira': { name: 'Pelusa', cat: 'ira', desc: 'Envidia leve y cotidiana. Los celos pequeños de cada día.', nivel: 5 },
  'desapego_ira': { name: 'Desapego', cat: 'ira', desc: 'Distancia emocional. La ira fría que ha decidido no volver a acercarse.', nivel: 5 },
  'desafecto_ira': { name: 'Desafecto', cat: 'ira', desc: 'Ausencia de afecto. La ira que ha apagado el amor.', nivel: 5 },
  'desorden_ira': { name: 'Desorden', cat: 'ira', desc: 'Caos interior provocado por la ira. La tormenta que desorganiza.', nivel: 5 },
  'displicencia_ira': { name: 'Displicencia', cat: 'ira', desc: 'Desdén y desgana. La ira expresada en la indiferencia despreciativa.', nivel: 5 },
  'resquemor_ira': { name: 'Resquemor', cat: 'ira', desc: 'Resentimiento que arde por dentro. La ira que no se va del todo.', nivel: 5 },

  'ansiedad': { name: 'Ansiedad', cat: 'ansiedad', desc: 'Estado de alerta sostenido ante amenazas percibidas. Cuando el sistema de alarma no se apaga.', nivel: 1 },
  'estres_nievel_uno': { name: 'Estrés', cat: 'ansiedad', desc: 'Respuesta de activación ante demandas que superan los recursos. El motor que puede convertirse en veneno.', nivel: 1 },
  'angustia_nievel_uno': { name: 'Angustia', cat: 'ansiedad', desc: 'Malestar profundo e indefinido. La ansiedad que oprime sin saber de qué huir.', nivel: 1 },
  'desesperacion_nievel_uno': { name: 'Desesperación', cat: 'ansiedad', desc: 'Ansiedad extrema sin salida percibida. El alma al borde de sus límites.', nivel: 1 },
  'preocupacion_nievel_uno': { name: 'Preocupación', cat: 'ansiedad', desc: 'Pensamiento repetitivo sobre posibles amenazas. La mente que no puede dejar de vigilar.', nivel: 1 },
  'depresion_tristeza': { name: 'Depresión', cat: 'ansiedad', desc: 'Estado de ánimo deprimido que afecta toda la vida. Cuando la tristeza se convierte en estado permanente.', nivel: 1 },
  'nerviosismo_ansiedad': { name: 'Nerviosismo', cat: 'ansiedad', desc: 'Agitación ansiosa moderada. El cuerpo en alerta sin saber por qué.', nivel: 2 },
  'hipocondria_ansiedad': { name: 'Hipocondría', cat: 'ansiedad', desc: 'Ansiedad focalizada en la salud. El miedo a la enfermedad que genera su propia enfermedad.', nivel: 2 },
  'inseguridad_ansiedad': { name: 'Inseguridad', cat: 'ansiedad', desc: 'Duda persistente sobre las propias capacidades. La ansiedad del yo que no confía en sí mismo.', nivel: 2 },
  'inquietud_ansiedad': { name: 'Inquietud', cat: 'ansiedad', desc: 'Agitación interior ante lo incierto. La ansiedad en su forma más cotidiana.', nivel: 2 },
  'desazon_ansiedad': { name: 'Desazón', cat: 'ansiedad', desc: 'Malestar vago e indefinido. La ansiedad que no sabe su nombre.', nivel: 2 },
  'zozobra_ansiedad': { name: 'Zozobra', cat: 'ansiedad', desc: 'Inquietud intensa ante el peligro. La ansiedad que hace tambalear.', nivel: 4 },
  'turbacion_ansiedad': { name: 'Turbación', cat: 'ansiedad', desc: 'Alteración del ánimo que nubla el juicio. La ansiedad que perturba.', nivel: 4 },
  'sindrome_abstinencia_ansiedad': { name: 'Síndrome de Abstinencia', cat: 'ansiedad', desc: 'Conjunto de síntomas al suprimir una sustancia o comportamiento. La ansiedad del cuerpo que exige.', nivel: 4 },
  'escrupulo_ansiedad': { name: 'Escrúpulo', cat: 'ansiedad', desc: 'Duda ansiosa sobre la corrección moral de las propias acciones.', nivel: 5 },
  'intriga_ansiedad': { name: 'Intriga', cat: 'ansiedad', desc: 'Curiosidad ansiosa ante lo oculto o misterioso. La ansiedad del que quiere saber.', nivel: 5 },
  'apuro_ansiedad': { name: 'Apuro', cat: 'ansiedad', desc: 'Urgencia ansiosa. La presión del tiempo que se acaba.', nivel: 5 },

  'emociones_sociales_y_morales': { name: 'Emociones Sociales y Morales', cat: 'emociones_sociales_y_morales', desc: 'Emociones que surgen de la vida en comunidad y del sentido moral. El alma social del ser humano.', nivel: 1 },
  'timidez_emociones_sociales_y_morales': { name: 'Timidez', cat: 'emociones_sociales_y_morales', desc: 'Inhibición ante la mirada ajena. El yo que se encoge ante el otro.', nivel: 2 },
  'verguenza_emociones_sociales_y_morales': { name: 'Vergüenza', cat: 'emociones_sociales_y_morales', desc: 'Dolor por la percepción de haber fallado a los propios estándares ante los demás.', nivel: 2 },
  'culpa_emociones_sociales_y_morales': { name: 'Culpa', cat: 'emociones_sociales_y_morales', desc: 'Malestar por haber transgredido valores propios. La conciencia que juzga y puede transformar.', nivel: 2 },
  'desprecio_emociones_sociales_y_morales': { name: 'Desprecio', cat: 'emociones_sociales_y_morales', desc: 'Evaluación negativa intensa del otro. La emoción más corrosiva socialmente.', nivel: 3 },
  'asco_moral_emociones_sociales_y_morales': { name: 'Asco Moral', cat: 'emociones_sociales_y_morales', desc: 'Repulsa ante lo que viola los valores morales. El sistema inmune de la sociedad.', nivel: 3 },
  'rubor_emociones_sociales_y_morales': { name: 'Rubor', cat: 'emociones_sociales_y_morales', desc: 'Enrojecimiento involuntario ante la exposición social. El cuerpo que delata la vergüenza.', nivel: 3 },
  'gratitud_emociones_sociales_y_morales': { name: 'Gratitud Social', cat: 'emociones_sociales_y_morales', desc: 'Reconocimiento de la deuda social. La gratitud como pegamento de la comunidad.', nivel: 3 },
  'orgullo_emociones_sociales_y_morales': { name: 'Orgullo', cat: 'emociones_sociales_y_morales', desc: 'Satisfacción por logros propios o de los nuestros. Puede elevar o separar.', nivel: 3 },
  'verguenza_ajena_emociones_sociales_y_morales': { name: 'Vergüenza Ajena', cat: 'emociones_sociales_y_morales', desc: 'Vergüenza por las acciones de otro. La empatía que se sonroja.', nivel: 3 },
  'embarazo_emociones_sociales_y_morales': { name: 'Embarazo', cat: 'emociones_sociales_y_morales', desc: 'Incomodidad social ante situaciones comprometidas. La vergüenza leve y cotidiana.', nivel: 3 },
  'elevacion_emociones_sociales_y_morales': { name: 'Elevación Moral', cat: 'emociones_sociales_y_morales', desc: 'Emoción de ser elevado por la bondad ajena. El corazón que se expande ante la virtud.', nivel: 4 },
  'indignacion_emociones_sociales_y_morales': { name: 'Indignación', cat: 'emociones_sociales_y_morales', desc: 'Ira moral ante la injusticia. La emoción que mueve hacia el cambio social.', nivel: 4 },
  'aversion_emociones_sociales_y_morales': { name: 'Aversión Moral', cat: 'emociones_sociales_y_morales', desc: 'Rechazo ante lo moralmente repugnante. El asco trasladado al plano ético.', nivel: 4 },
  'cohibicion_emociones_sociales_y_morales': { name: 'Cohibición', cat: 'emociones_sociales_y_morales', desc: 'Inhibición por la presencia o juicio ajeno. La vergüenza que paraliza.', nivel: 4 },
  'ridiculo_emociones_sociales_y_morales': { name: 'Ridículo', cat: 'emociones_sociales_y_morales', desc: 'Vergüenza por haber sido objeto de burla. La humillación pública.', nivel: 4 },
  'pudor_emociones_sociales_y_morales': { name: 'Pudor', cat: 'emociones_sociales_y_morales', desc: 'Vergüenza ante la exposición de lo íntimo. El límite entre lo privado y lo público.', nivel: 4 },
  'recato_emociones_sociales_y_morales': { name: 'Recato', cat: 'emociones_sociales_y_morales', desc: 'Moderación y reserva en la expresión. La vergüenza convertida en virtud.', nivel: 4 },
  'empatia_emociones_sociales_y_morales': { name: 'Empatía Moral', cat: 'emociones_sociales_y_morales', desc: 'Capacidad de sentir el impacto moral de las acciones en el otro.', nivel: 4 },
  'contriccion_emociones_sociales_y_morales': { name: 'Contrición', cat: 'emociones_sociales_y_morales', desc: 'Dolor profundo por haber hecho el mal. La culpa que lleva al cambio.', nivel: 4 },
  'azaramiento_emociones_sociales_y_morales': { name: 'Azaramiento', cat: 'emociones_sociales_y_morales', desc: 'Turbación y vergüenza repentinas. El rubor del alma pillada en falta.', nivel: 4 },
  'corte_emociones_sociales_y_morales': { name: 'Corte', cat: 'emociones_sociales_y_morales', desc: 'Vergüenza social intensa. El momento en que el suelo parece abrirse.', nivel: 4 },
  'culpa_empatica_emociones_sociales_y_morales': { name: 'Culpa Empática', cat: 'emociones_sociales_y_morales', desc: 'Culpa por el daño causado al otro. La conciencia que sintió al otro sufrir.', nivel: 4 },
  'culpa_ansiosa_emociones_sociales_y_morales': { name: 'Culpa Ansiosa', cat: 'emociones_sociales_y_morales', desc: 'Culpa que genera espiral de ansiedad. El yo que no puede perdonarse.', nivel: 4 },
  'arrepentimiento_emociones_sociales_y_morales': { name: 'Arrepentimiento', cat: 'emociones_sociales_y_morales', desc: 'Dolor por acciones pasadas y deseo de haberlas hecho diferente.', nivel: 4 },
  'remordimiento_emociones_sociales_y_morales': { name: 'Remordimiento', cat: 'emociones_sociales_y_morales', desc: 'Culpa persistente y dolorosa. La conciencia que no deja dormir.', nivel: 4 },
  'solastalgia_emociones_sociales_y_morales': { name: 'Solastalgia', cat: 'emociones_sociales_y_morales', desc: 'Dolor por la degradación del entorno amado. La nostalgia del lugar que ya no existe.', nivel: 5 },
  'compasion_emociones_sociales_y_morales': { name: 'Compasión Social', cat: 'emociones_sociales_y_morales', desc: 'Compasión extendida a toda la comunidad. El amor que abraza el sufrimiento colectivo.', nivel: 5 },
  'patriotismo_emociones_sociales_y_morales': { name: 'Patriotismo', cat: 'emociones_sociales_y_morales', desc: 'Amor a la patria y la comunidad de origen. Puede unir o excluir.', nivel: 5 },
  'piedad_emociones_sociales_y_morales': { name: 'Piedad Social', cat: 'emociones_sociales_y_morales', desc: 'Compasión activa ante el sufrimiento ajeno en la comunidad.', nivel: 5 },
  'kama_muta_emociones_sociales_y_morales': { name: 'Kama Muta', cat: 'emociones_sociales_y_morales', desc: 'Emoción de ser movido por el amor. Escalofríos ante la bondad o la unión.', nivel: 5 },
  'sonrojo_emociones_sociales_y_morales': { name: 'Sonrojo', cat: 'emociones_sociales_y_morales', desc: 'Enrojecimiento emocional ante la exposición. La vergüenza que se ve.', nivel: 5 },
  'bochorno_emociones_sociales_y_morales': { name: 'Bochorno', cat: 'emociones_sociales_y_morales', desc: 'Vergüenza intensa y calurosa. El calor de la exposición pública.', nivel: 5 },
  'solifilia_emociones_sociales_y_morales': { name: 'Solifilia', cat: 'emociones_sociales_y_morales', desc: 'Amor por el planeta Tierra como hogar común. La emoción ecológica más profunda.', nivel: 5 },

  'actitudes': { name: 'Actitudes', cat: 'actitudes', desc: 'Disposiciones mentales y emocionales que determinan cómo nos relacionamos con la vida.', nivel: 1 },
  'coraje_actitudes': { name: 'Coraje', cat: 'actitudes', desc: 'Valentía para actuar a pesar del miedo. No es ausencia de temor sino avanzar con él.', nivel: 2 },
  'resiliencia_actitudes': { name: 'Resiliencia', cat: 'actitudes', desc: 'Capacidad de recuperarse y crecer tras la adversidad. El árbol que se dobla pero no se rompe.', nivel: 2 },
  'temeridad_actitudes': { name: 'Temeridad', cat: 'actitudes', desc: 'Valentía sin prudencia. El coraje que no mide los riesgos.', nivel: 3 },
  'atrevimiento_actitudes': { name: 'Atrevimiento', cat: 'actitudes', desc: 'Disposición a actuar más allá de los límites habituales. El coraje en acción.', nivel: 3 },
  'valentia_actitudes': { name: 'Valentía', cat: 'actitudes', desc: 'Fortaleza para enfrentar lo difícil. El alma que no huye de lo que teme.', nivel: 3 },
  'mindset_actitudes': { name: 'Mindset', cat: 'actitudes', desc: 'Conjunto de creencias sobre el propio potencial. La actitud que determina el crecimiento.', nivel: 3 },
  'fortaleza_actitudes': { name: 'Fortaleza', cat: 'actitudes', desc: 'Solidez interior que resiste la adversidad. La virtud del alma que permanece.', nivel: 3 },
  'actitud_negativa_actitudes': { name: 'Actitud Negativa', cat: 'actitudes', desc: 'Disposición que anticipa lo peor y resiste el cambio.', nivel: 4 },
  'actitud_cerrada_actitudes': { name: 'Actitud Cerrada', cat: 'actitudes', desc: 'Impermeabilidad a nuevas ideas o perspectivas. La mente que no puede abrirse.', nivel: 4 },
  'animo_negativo_actitudes': { name: 'Ánimo Negativo', cat: 'actitudes', desc: 'Estado de baja energía y disposición pesimista sostenida.', nivel: 4 },
  'predisposiciones_actitudes': { name: 'Predisposiciones', cat: 'actitudes', desc: 'Tendencias previas que colorean la percepción antes de la experiencia.', nivel: 4 },
  'animo_positivo_actitudes': { name: 'Ánimo Positivo', cat: 'actitudes', desc: 'Estado de energía y disposición favorable. La actitud que facilita el florecimiento.', nivel: 4 },
  'actitud_positiva_actitudes': { name: 'Actitud Positiva', cat: 'actitudes', desc: 'Disposición que anticipa posibilidades y abraza el cambio.', nivel: 4 },
  'grit_actitudes': { name: 'Grit (Persistencia)', cat: 'actitudes', desc: 'Combinación de pasión y perseverancia a largo plazo. Angela Duckworth: el predictor del éxito.', nivel: 4 },
  'intenciones_actitudes': { name: 'Intenciones', cat: 'actitudes', desc: 'Propósitos conscientes que dirigen la acción. La voluntad con dirección.', nivel: 4 },

  'emociones_esteticas': { name: 'Emociones Estéticas', cat: 'emociones_esteticas', desc: 'Respuestas emocionales ante la belleza y el arte. El alma que es movida por lo sublime.', nivel: 1 },
  'sindrome_de_stendhal_emociones_esteticas': { name: 'Síndrome de Stendhal', cat: 'emociones_esteticas', desc: 'Abrumamiento físico y emocional ante la belleza extrema del arte. Cuando lo bello supera al ser.', nivel: 5 },
}
